### ISSUE TITLE
Problem with installation. 

### ISSUE THREAD

**Issue by lillipu** [AndrewFromMelbourne/raspi2raspi#4]
Dear Andrew,
Thank you for sharing your tool. It seems this is exactly what I need. 
However, I am having some problems with the installation on my raspberry pi 3, running raspian jessie. 
First installation of libbsd-dev failes (unable to locate package libbsd-dev).
I cloned raspi2raspi and run cmake (build files succesfully written to /home/pi/build, however the make command returns this error: 

/home/pi/raspi2raspi/raspi2raspi.c:43:25: fatal error: bsd/libutil.h: No such file or directory
 #include <bsd/libutil.h>
                         ^
compilation terminated.
CMakeFiles/raspi2raspi.dir/build.make:62: recipe for target 'CMakeFiles/raspi2raspi.dir/raspi2raspi.c.o' failed
make[2]: *** [CMakeFiles/raspi2raspi.dir/raspi2raspi.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/raspi2raspi.dir/all' failed
make[1]: *** [CMakeFiles/raspi2raspi.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

So I am a bit stuck. Could you may be help me to look in the right direction to solve this problem?

Could you also tell me if it is possible to turn the sharing on and off for example through a python script and if it is possible to use the DSI screen as 'slave' but keep touch sensitivity together with a 'master' HDMI monitor? 

Many thanks!

**Comment by lillipu** [comment]
There was a problem in my /etc/apt/sources.list. Now it installed perfectly.

**Comment by AndrewFromMelbourne** [comment]
Glad you sorted it out.

@lillipu a simple way to turn sharing on or off would be using the systemctl command. To turn it off use

sudo systemctl stop raspi2raspi

and to turn it back on

sudo systemctl start raspi2raspi

or you could start raspi2raspi within python and then kill it to turn off mirroring. I hope that helps.
